# Generated by Django 3.0.4 on 2020-04-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('send_log', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('file_format', models.CharField(max_length=100)),
                ('include_all', models.BooleanField()),
                ('log_type', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PacketFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=254)),
                ('asName', models.CharField(max_length=254)),
                ('proto', models.CharField(max_length=254)),
                ('source', models.GenericIPAddressField()),
                ('destination', models.GenericIPAddressField()),
                ('direction', models.CharField(max_length=254)),
                ('action', models.CharField(max_length=254)),
                ('category', models.CharField(max_length=254)),
                ('reason', models.TextField(blank=True)),
                ('list', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('device', models.TextField(blank=True)),
                ('email_alerts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EmailAlerts')),
            ],
        ),
        migrations.CreateModel(
            name='DomainFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=254)),
                ('proto', models.CharField(max_length=254)),
                ('source', models.GenericIPAddressField()),
                ('destination', models.GenericIPAddressField()),
                ('action', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('device', models.TextField(blank=True)),
                ('email_alerts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EmailAlerts')),
            ],
        ),
    ]
